# Generated by Django 3.0.5 on 2020-09-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='lang',
            new_name='language',
        ),
    ]
