# Generated by Django 3.0.5 on 2020-09-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myweb', '0002_auto_20200909_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='framework',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Express.js', 'Express.js')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='language',
            field=models.CharField(blank=True, choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('C++', 'C++'), ('Html', 'Html'), ('Css', 'Css'), ('SQL', 'SQL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
