# Generated by Django 3.0.5 on 2020-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20200910_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='framework',
        ),
        migrations.AlterField(
            model_name='upload',
            name='language',
            field=models.CharField(blank=True, choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('C++', 'C++'), ('Html', 'Html'), ('Css', 'Css'), ('SQL', 'SQL'), ('Django', 'Django'), ('Flask', 'Flask'), ('Express.js', 'Express.js')], max_length=100, null=True),
        ),
    ]
