# Generated by Django 3.0.5 on 2020-09-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_upload_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='liked',
        ),
    ]
