# Generated by Django 3.0.5 on 2020-09-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
