# Generated by Django 3.1.1 on 2020-09-13 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myweb', '0009_upload_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='language',
            field=models.CharField(blank=True, choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('C++', 'C++'), ('Html', 'Html'), ('Css', 'Css'), ('SQL', 'SQL'), ('Django', 'Django'), ('Flask', 'Flask'), ('Express.js', 'Express.js'), ('Algorithm&DataStructure', 'Algorithm&DataStructure'), ('TimeComplexity', 'TimeComplexity')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
